name: Generate LineageOS Device Tree – Galaxy A56

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate-device-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git unzip lz4 simg2img

      - name: Clone firmware dump
        run: |
          git clone https://gitgud.io/Van-Firmware-Dumps/samsung/a56x.git firmware
          cd firmware
          git checkout 7ae13010055f8646e07c70b26fd0c536dc102de3

      - name: List firmware contents
        run: |
          echo "Firmware dump contents:"
          find firmware -maxdepth 2 | sed 's/^/  /'

      - name: Create device tree scaffold
        run: |
          mkdir -p device/samsung/a56x

          # AndroidProducts.mk (single line)
          echo 'PRODUCT_MAKEFILES := $(LOCAL_DIR)/device.mk' > device/samsung/a56x/AndroidProducts.mk

          # device.mk
          cat > device/samsung/a56x/device.mk <<'EOF'
PRODUCT_NAME := a56x
PRODUCT_BRAND := samsung
PRODUCT_MODEL := SM-A566B
PRODUCT_DEVICE := a56x
PRODUCT_MANUFACTURER := samsung

$(call inherit-product, vendor/lineage/config/common.mk)

PRODUCT_PACKAGES += \
    org.lineageos.settings
EOF

          # BoardConfig.mk
          cat > device/samsung/a56x/BoardConfig.mk <<'EOF'
TARGET_ARCH := arm64
TARGET_BOARD_PLATFORM := qcom
BOARD_KERNEL_IMAGE := kernel
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
EOF

          # vendorsetup.sh
          echo 'add_lunch_combo lineage_a56x-userdebug' > device/samsung/a56x/vendorsetup.sh
          chmod +x device/samsung/a56x/vendorsetup.sh

      - name: Generate proprietary-files.txt template
        run: |
          mkdir -p device/samsung/a56x
          echo "# Proprietary blobs from firmware dump" > device/samsung/a56x/proprietary-files.txt
          grep -R ".so" firmware/vendor >> device/samsung/a56x/proprietary-files.txt || true
          grep -R "libwifihal" firmware >> device/samsung/a56x/proprietary-files.txt || true

      - name: Package device tree
        run: |
          mkdir -p output
          cd device/samsung
          zip -r ../../output/a56x_device_tree.zip a56x

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: a56x_device_tree
          path: output/a56x_device_tree.zip