name: Generate Device Tree A56x

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-device-tree:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ${{ github.workspace }}/a56x_firmware
      GIT_REPO_DIR: ${{ github.workspace }}/a56x_device_tree
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential device-tree-compiler simg2img cpio

      - name: Run device tree generation script
        run: |
          mkdir -p scripts
          curl -o scripts/workflow_generate_device_tree.sh https://raw.githubusercontent.com/<YOUR_USER>/<YOUR_REPO>/main/scripts/workflow_generate_device_tree.sh
          chmod +x scripts/workflow_generate_device_tree.sh
          bash scripts/workflow_generate_device_tree.sh

      - name: Commit generated device tree
        run: |
          cd $GIT_REPO_DIR
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update device tree A56x from firmware" || echo "No changes to commit"
          git push origin device_tree_a56x || echo "Could not push (maybe first time)"