name: Build Device Tree

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-device-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget unzip python3 python3-pip lz4 simg2img

      - name: Clone Device Repo
        run: |
          git clone https://gitgud.io/Van-Firmware-Dumps/samsung/a56x.git device/samsung/a56x

      - name: Prepare Vendor Extract (optional)
        run: |
          mkdir -p vendor/samsung/a56x
          # You can place stock firmware here and mount images
          # ./extract-files.sh ~/firmware/system ~/firmware/vendor

      - name: Package Device Tree
        run: |
          mkdir -p output
          zip -r output/device_samsung_a56x.zip device/samsung/a56x vendor/samsung/a56x || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: device_samsung_a56x
          path: output/device_samsung_a56x.zip
